=== eitch/intruvia/intruvia-core/src/main/resources/model/StrolchModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2025 atexxi Systems AG <dev@atexxi.ch>. All rights reserved.
  ~
  ~ This source code is proprietary and confidential. Unauthorized copying, modification,
  ~ distribution, or use of this code, via any medium, is strictly prohibited without prior
  ~ written permission from atexxi Systems AG.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://strolch.li/schema/StrolchModel.xsd"
		   xmlns="https://strolch.li/schema/StrolchModel.xsd"
		   elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:annotation>
		<xs:documentation>This is Version 1.6.x of the StrolchModel XSD.</xs:documentation>
	</xs:annotation>

	<xs:element name="StrolchModel" type="StrolchModelType"/>

	<xs:complexType name="StrolchModelType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:choice>
				<xs:element type="IncludeFileType" name="IncludeFile" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element type="OrderType" name="Order" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element type="ResourceType" name="Resource" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element type="ActivityType" name="Activity" maxOccurs="unbounded" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="IncludeFileType">
		<xs:attribute type="xs:string" name="file"/>
	</xs:complexType>

	<xs:complexType name="VersionType">
		<xs:attribute type="xs:int" name="Version" use="required"/>
		<xs:attribute type="xs:string" name="CreatedBy" use="required"/>
		<xs:attribute type="xs:string" name="UpdatedBy" use="required"/>
		<xs:attribute type="xs:dateTime" name="Created" use="required"/>
		<xs:attribute type="xs:dateTime" name="Updated" use="required"/>
		<xs:attribute type="xs:string" name="Deleted" use="required"/>
	</xs:complexType>

	<xs:complexType name="OrderType">
		<xs:sequence>
			<xs:element type="VersionType" name="Version" maxOccurs="1" minOccurs="0"/>
			<xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="Id" use="required"/>
		<xs:attribute type="xs:string" name="Name" use="required"/>
		<xs:attribute type="xs:string" name="Type" use="required"/>
		<xs:attribute type="xs:dateTime" name="Date" use="optional"/>
		<xs:attribute type="StateType" name="State" use="optional"/>
	</xs:complexType>

	<xs:complexType name="ResourceType">
		<xs:sequence>
			<xs:element type="VersionType" name="Version" maxOccurs="1" minOccurs="0"/>
			<xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="TimedStateType" name="TimedState" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="Id" use="required"/>
		<xs:attribute type="xs:string" name="Name" use="required"/>
		<xs:attribute type="xs:string" name="Type" use="required"/>
	</xs:complexType>

	<xs:complexType name="ActivityType">
		<xs:sequence>
			<xs:element type="VersionType" name="Version" maxOccurs="1" minOccurs="0"/>
			<xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:choice>
					<xs:element type="ActionType" name="Action" maxOccurs="unbounded" minOccurs="0"/>
					<xs:element type="ActivityType" name="Activity" maxOccurs="unbounded" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
			<xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="Id" use="required"/>
		<xs:attribute type="xs:string" name="Name" use="required"/>
		<xs:attribute type="xs:string" name="Type" use="required"/>
		<xs:attribute type="TimeOrderingType" name="TimeOrdering" use="required"/>
	</xs:complexType>

	<xs:complexType name="ActionType">
		<xs:sequence>
			<xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
			<xs:element type="ValueChangeType" name="ValueChange" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="Id" use="required"/>
		<xs:attribute type="xs:string" name="Name" use="required"/>
		<xs:attribute type="xs:string" name="ResourceId" use="optional"/>
		<xs:attribute type="xs:string" name="ResourceType" use="optional"/>
		<xs:attribute type="StateType" name="State" use="optional"/>
		<xs:attribute type="xs:string" name="Type" use="required"/>
	</xs:complexType>

	<xs:complexType name="ParameterBagType">
		<xs:sequence>
			<xs:element type="ParameterType" name="Parameter" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="Id" use="required"/>
		<xs:attribute type="xs:string" name="Name" use="required"/>
		<xs:attribute type="xs:string" name="Type" use="required"/>
	</xs:complexType>

	<xs:complexType name="ParameterType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="Id" use="required"/>
				<xs:attribute type="xs:string" name="Name" use="required"/>
				<xs:attribute type="ParameterValueType" name="Type" use="required"/>
				<xs:attribute type="xs:string" name="Value" use="optional"/>
				<xs:attribute type="xs:string" name="Interpretation" use="optional"/>
				<xs:attribute type="xs:string" name="Uom" use="optional"/>
				<xs:attribute type="xs:boolean" name="Hidden" use="optional"/>
				<xs:attribute type="xs:int" name="Index" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="PoliciesType">
		<xs:sequence>
			<xs:element type="PolicyType" name="Policy" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PolicyType">
		<xs:attribute type="xs:string" name="Type" use="required"/>
		<xs:attribute type="xs:string" name="Value" use="required"/>
	</xs:complexType>

	<xs:complexType name="TimedStateType">
		<xs:sequence>
			<xs:element type="ValueType" name="Value" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="Id" use="required"/>
		<xs:attribute type="xs:string" name="Name" use="required"/>
		<xs:attribute type="TimedStateTypeType" name="Type" use="required"/>
		<xs:attribute type="xs:string" name="Interpretation" use="optional"/>
		<xs:attribute type="xs:string" name="Uom" use="optional"/>
		<xs:attribute type="xs:boolean" name="Hidden" use="optional"/>
		<xs:attribute type="xs:int" name="Index" use="optional"/>
	</xs:complexType>

	<xs:complexType name="ValueType">
		<xs:attribute type="xs:dateTime" name="Time" use="required"/>
		<xs:attribute type="xs:string" name="Value" use="required"/>
	</xs:complexType>

	<xs:complexType name="ValueChangeType">
		<xs:attribute type="xs:string" name="StateId" use="optional"/>
		<xs:attribute type="xs:dateTime" name="Time" use="required"/>
		<xs:attribute type="xs:string" name="Value" use="required"/>
		<xs:attribute type="TimedStateTypeType" name="Type" use="required"/>
	</xs:complexType>

	<xs:simpleType name="StateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Created"/>
			<xs:enumeration value="Planning"/>
			<xs:enumeration value="Planned"/>
			<xs:enumeration value="Execution"/>
			<xs:enumeration value="Stopped"/>
			<xs:enumeration value="Warning"/>
			<xs:enumeration value="Error"/>
			<xs:enumeration value="Executed"/>
			<xs:enumeration value="Closed"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TimeOrderingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Series"/>
			<xs:enumeration value="Parallel"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ParameterValueType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="String"/>
			<xs:enumeration value="Text"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Long"/>
			<xs:enumeration value="Float"/>
			<xs:enumeration value="Date"/>
			<xs:enumeration value="Duration"/>
			<xs:enumeration value="StringList"/>
			<xs:enumeration value="IntegerList"/>
			<xs:enumeration value="FloatList"/>
			<xs:enumeration value="LongList"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TimedStateTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Boolean"/>
			<xs:enumeration value="Integer"/>
			<xs:enumeration value="Float"/>
			<xs:enumeration value="Long"/>
			<xs:enumeration value="FloatList"/>
			<xs:enumeration value="StringSet"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== eitch/intruvia/intruvia-core/src/main/resources/model/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<StrolchModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://strolch.li/schema/StrolchModel.xsd"
              xsi:schemaLocation="https://strolch.li/schema/StrolchModel.xsd https://strolch.li/schema/StrolchModel.xsd">
    <Resource Id="SecurityEvent" Name="SecurityEvent" Type="SecurityEvent">
        <ParameterBag Id="envelope" Name="envelope" Type="envelope">
            <Parameter Id="schemaVersion" Name="schemaVersion" Type="Integer" Value="0"/>
            <Parameter Id="sequence" Name="sequence" Type="Long" Value="0"/>
            <Parameter Id="category" Name="category" Type="String" Value=""/>
            <Parameter Id="action" Name="action" Type="String" Value=""/>
            <Parameter Id="occurredAt" Name="occurredAt" Type="String" Value=""/>
            <Parameter Id="receivedAt" Name="receivedAt" Type="String" Value=""/>
        </ParameterBag>
        <ParameterBag Id="source" Name="source" Type="source">
            <Parameter Id="type" Name="type" Type="String" Value=""/>
            <Parameter Id="instanceId" Name="instanceId" Type="String" Value=""/>
            <Parameter Id="eventId" Name="eventId" Type="String" Value=""/>
        </ParameterBag>
        <ParameterBag Id="subject" Name="subject" Type="subject">
            <Parameter Id="ip" Name="ip" Type="String" Value=""/>
        </ParameterBag>
        <ParameterBag Id="observer" Name="observer" Type="observer">
            <Parameter Id="id" Name="id" Type="String" Value=""/>
        </ParameterBag>
        <ParameterBag Id="attributes.fail2ban" Name="attributes.fail2ban" Type="attributes.fail2ban">
            <Parameter Id="jail" Name="jail" Type="String" Value=""/>
            <Parameter Id="failures" Name="failures" Type="Integer" Value="0"/>
        </ParameterBag>
        <ParameterBag Id="geo" Name="geo" Type="geo">
            <Parameter Id="status" Name="status" Type="String" Value=""/>
            <Parameter Id="countryCode" Name="countryCode" Type="String" Value=""/>
            <Parameter Id="countryName" Name="countryName" Type="String" Value=""/>
            <Parameter Id="region" Name="region" Type="String" Value=""/>
            <Parameter Id="city" Name="city" Type="String" Value=""/>
            <Parameter Id="latitude" Name="latitude" Type="Float" Value="0"/>
            <Parameter Id="longitude" Name="longitude" Type="Float" Value="0"/>
            <Parameter Id="accuracyRadiusKm" Name="accuracyRadiusKm" Type="Float" Value="0"/>
            <Parameter Id="provider" Name="provider" Type="String" Value=""/>
            <Parameter Id="databaseEdition" Name="databaseEdition" Type="String" Value=""/>
            <Parameter Id="databaseBuildAt" Name="databaseBuildAt" Type="String" Value=""/>
            <Parameter Id="lookedUpAt" Name="lookedUpAt" Type="String" Value=""/>
        </ParameterBag>
    </Resource>
    <Resource Id="IngestReceipt" Name="IngestReceipt" Type="IngestReceipt">
        <ParameterBag Id="parameters" Name="parameters" Type="parameters">
            <Parameter Id="instanceId" Name="instanceId" Type="String" Value=""/>
            <Parameter Id="sourceEventId" Name="sourceEventId" Type="String" Value=""/>
            <Parameter Id="payloadDigest" Name="payloadDigest" Type="String" Value=""/>
            <Parameter Id="eventId" Name="eventId" Type="String" Value=""/>
            <Parameter Id="sequence" Name="sequence" Type="Long" Value="0"/>
            <Parameter Id="expiresAt" Name="expiresAt" Type="String" Value=""/>
        </ParameterBag>
    </Resource>
    <Resource Id="EventStreamState" Name="EventStreamState" Type="EventStreamState">
        <ParameterBag Id="parameters" Name="parameters" Type="parameters">
            <Parameter Id="lastCommittedSequence" Name="lastCommittedSequence" Type="Long" Value="0"/>
            <Parameter Id="minAfter" Name="minAfter" Type="Long" Value="0"/>
        </ParameterBag>
    </Resource>
</StrolchModel>
